### ISSUE TITLE
extract_items 的问题

### ISSUE THREAD

**Issue by Akeepers** [weizhepei/HBT#32]
extract_items 获取subject 对应文本的部分是否存在问题? 没有想通，望得到解答，麻烦了~

如下代码中的sub_heads, sub_tails 代表head和tail所有可能位置的candidates

* 其中sub_head 和 sub_tail 应该对应的都是span的闭区间，对tokens做切片时为何不sub_tail+1 

```
 sub_heads_logits, sub_tails_logits = subject_model.predict([token_ids, segment_ids])
    sub_heads, sub_tails = np.where(sub_heads_logits[0] > h_bar)[0], np.where(sub_tails_logits[0] > t_bar)[0]
    subjects = []
    for sub_head in sub_heads:
        sub_tail = sub_tails[sub_tails >= sub_head]
        if len(sub_tail) > 0:
            sub_tail = sub_tail[0] 
            subject = tokens[sub_head: sub_tail]
            subjects.append((subject, sub_head, sub_tail)) 
```

从data_loader中代码来看，构建gold_label时，subject 和object 文本span 都是闭区间 (其中是sub_head_idx + len(triple[0]) - 1)

```
                for triple in line['triple_list']:
                    triple = (self.tokenizer.tokenize(triple[0])[1:-1], triple[1], self.tokenizer.tokenize(triple[2])[1:-1])
                    sub_head_idx = find_head_idx(tokens, triple[0])
                    obj_head_idx = find_head_idx(tokens, triple[2])
                    if sub_head_idx != -1 and obj_head_idx != -1:
                        sub = (sub_head_idx, sub_head_idx + len(triple[0]) - 1)
                        if sub not in s2ro_map:
                            s2ro_map[sub] = []
                        s2ro_map[sub].append((obj_head_idx,
                                           obj_head_idx + len(triple[2]) - 1,
                                           self.rel2id[triple[1]]))
```

**Comment by Akeepers** [comment]
更新，发现keras_bert的tokenizer 会在分词之后，每个token 之后加入[unused1] 这样的标签，如下:
```
句子Tokenization之后的结果： ['[CLS]', 'Ye', '##lling', '##bo', '[unused1]', ',', '[unused1]', 'a', '[unused1]', 'nature', '[unused1]', 'reserve', '[unused1]', 'in', '[unused1]', 'southern', '[unused1]', 'Australia', '[unused1]', ',', '[unused1]', 'is', '[unused1]', 'adjacent', '[unused1]', 'to', '[unused1]', 'olive', '[unused1]', 'grove', '##s', '[unused1]', 'that', '[unused1]', 'Howard', '[unused1]', 'Mel', '##tz', '##er', '[unused1]', 'planted', '[unused1]', 'more', '[unused1]', 'than', '[unused1]', '10', '[unused1]', 'years', '[unused1]', 'ago', '[unused1]', '.', '[unused1]', '[SEP]']
原始三元组：('Australia', '/location/location/contains', 'Yellingbo')
三元组Tokenization之后的结果：(['Australia', '[unused1]'], '/location/location/contains', ['Ye', '##lling', '##bo', '[unused1]'])
```

有额外的疑问，主要是这么做的意思：

1. 额外加入'[unused1] 标签相当于减少了max_seq_len的大小
2. 这个频繁出现的[unused] 标签对于bert 编码embedding是否会存在影响，理论上是会的
3. 把需要抽取的span 尾部设在[unused1]标签，意义是什么？

**Comment by xpxpx** [comment]
作者这么做是因为bert会将词拆成亚词（subword），但是做三元组提取时，是提取词，为了避免边界混淆，所以在每个词被拆解成亚词之后，加上一个额外的token来标注这是词的边界。

**Comment by Akeepers** [comment]
谢谢你的回复~ 实际上我的问题是这样的

1. 在Tokenization的结果中引入了额外的标记[unused1]，这个标记实际并未在原始文本中出现，那么一定会对bert编码特征的过程造成影响 & 如果仅仅只是为了避免边界混淆，那么是不需要这样做的
2. 引入[unused] 标签还会 减少max_seq_len的副作用
3. span的尾部是[unused1] ，这个并未在原始文本中出现，也没有实际的语义，即使这样work，又该怎么解释这个结果呢？泛化性会好吗？
4. 我也做过一些利用 span prediction 处理序列标注问题的工作，之前没遇到过加[unused1]标记的情况

**Comment by xpxpx** [comment]
这里的[unused1]其实类似[CLS]、[SEP]这样的标签，确实没有实际的意义，但却是必要的。我复现过作者的工作，刚开始结果很差，后来发现原因是没有加这个[unused1]标签。
一个词，在bert中，会被分成亚词，比如apple，可能会被拆成ap和ple，在作者的方法中，会识别一个实体的头位置和尾位置，如果不加边界标注，可能会将边界识别成ap，而不是ple。

**Comment by Akeepers** [comment]
谢谢啦，我也是用pytorch复现的时候，没加[unused1]标记，结果会差10个点。但是我并不觉得在输入文本加额外标记是一种唯一的做法，在span 解码的时候处理，可能会更优雅，也更合理

**Comment by janenie** [comment]
> extract_items 获取subject 对应文本的部分是否存在问题? 没有想通，望得到解答，麻烦了~
> 
> 如下代码中的sub_heads, sub_tails 代表head和tail所有可能位置的candidates
> 
> * 其中sub_head 和 sub_tail 应该对应的都是span的闭区间，对tokens做切片时为何不sub_tail+1
> 
> ```
>  sub_heads_logits, sub_tails_logits = subject_model.predict([token_ids, segment_ids])
>     sub_heads, sub_tails = np.where(sub_heads_logits[0] > h_bar)[0], np.where(sub_tails_logits[0] > t_bar)[0]
>   
想问下题主不觉得这一段解码的效率很低么，都只能是非batch的

**Comment by Akeepers** [comment]
> > extract_items 获取subject 对应文本的部分是否存在问题? 没有想通，望得到解答，麻烦了~
> > 如下代码中的sub_heads, sub_tails 代表head和tail所有可能位置的candidates
> > 
> > * 其中sub_head 和 sub_tail 应该对应的都是span的闭区间，对tokens做切片时为何不sub_tail+1
> > 
> > ```
> >  sub_heads_logits, sub_tails_logits = subject_model.predict([token_ids, segment_ids])
> >     sub_heads, sub_tails = np.where(sub_heads_logits[0] > h_bar)[0], np.where(sub_tails_logits[0] > t_bar)[0]
> >   
> > ```
> 
> 想问下题主不觉得这一段解码的效率很低么，都只能是非batch的

可以改一下，我改成按batch处理的，infer速度从1min+ 到了10 second +

**Comment by tiger-jie** [comment]
> 谢谢啦，我也是用pytorch复现的时候，没加[unused1]标记，结果会差10个点。但是我并不觉得在输入文本加额外标记是一种唯一的做法，在span 解码的时候处理，可能会更优雅，也更合理
是啊，我认为这个unsed太占长度了，如果是长序列该怎么办

**Comment by janenie** [comment]
有一个training data的preprocessing问题，在data_generator类中，在处理object entity的时候，用了一个random.choice函数选出了某一个subject entity下对应的所有关系，并没有选取所有的subject entity。个人对这一块代码有疑惑，因为subject entity在当前的输入语句中全部标记了出来，但是object对应的entity仅选取某一个subject下的关系对应的实体，这是否会导致有问题？

**Comment by Akeepers** [comment]
其实还好，你可以理解为subject 和 object是一个多任务学习，最后是subject 的训练数据，会被多训练，相当于对subject任务数据做了过采样。

我觉得repo的实现不算最优，可以试试将数据按object拆分，应该训练过程 更稳定 & 收敛更快

**Comment by Akeepers** [comment]
> 更新，发现keras_bert的tokenizer 会在分词之后，每个token 之后加入[unused1] 这样的标签，如下:
> 
> ```
> 句子Tokenization之后的结果： ['[CLS]', 'Ye', '##lling', '##bo', '[unused1]', ',', '[unused1]', 'a', '[unused1]', 'nature', '[unused1]', 'reserve', '[unused1]', 'in', '[unused1]', 'southern', '[unused1]', 'Australia', '[unused1]', ',', '[unused1]', 'is', '[unused1]', 'adjacent', '[unused1]', 'to', '[unused1]', 'olive', '[unused1]', 'grove', '##s', '[unused1]', 'that', '[unused1]', 'Howard', '[unused1]', 'Mel', '##tz', '##er', '[unused1]', 'planted', '[unused1]', 'more', '[unused1]', 'than', '[unused1]', '10', '[unused1]', 'years', '[unused1]', 'ago', '[unused1]', '.', '[unused1]', '[SEP]']
> 原始三元组：('Australia', '/location/location/contains', 'Yellingbo')
> 三元组Tokenization之后的结果：(['Australia', '[unused1]'], '/location/location/contains', ['Ye', '##lling', '##bo', '[unused1]'])
> ```
> 
> 有额外的疑问，主要是这么做的意思：
> 
> 1. 额外加入'[unused1] 标签相当于减少了max_seq_len的大小
> 2. 这个频繁出现的[unused] 标签对于bert 编码embedding是否会存在影响，理论上是会的
> 3. 把需要抽取的span 尾部设在[unused1]标签，意义是什么？

该问题仍然保留，这是提这个问题的初衷~ 望解答

**Comment by tiger-jie** [comment]
谢谢您的解答，我还有一个问题劳烦解答一下。对于很长的text来说，unused的使用会截断很多的单词，这种情况有没有什么好的解决办法


 
---原始邮件---
发件人: "杨攀"<notifications@github.com&gt;
发送时间: 2020年10月10日 09:06:59
收件人: "weizhepei/CasRel"<CasRel@noreply.github.com&gt;;
抄送: "tiger-jie"<1984223979@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [weizhepei/CasRel] extract_items 的问题 (#32)




 
其实还好，你可以理解为subject 和 object是一个多任务学习，最后是subject 的训练数据，会被多训练，相当于对subject任务数据做了过采样。
 
我觉得repo的实现不算最优，可以试试将数据按object拆分，应该训练过程 更稳定 &amp; 收敛更快

**Comment by Akeepers** [comment]
我觉得使用[unused] 副作用很大 & 说不通，我觉得还是不这么用吧。就用下这个工作的思想就好

> 谢谢您的解答，我还有一个问题劳烦解答一下。对于很长的text来说，unused的使用会截断很多的单词，这种情况有没有什么好的解决办法
> […](#)
> ---原始邮件--- 发件人: "杨攀"<notifications@github.com&gt; 发送时间: 2020年10月10日 09:06:59 收件人: "weizhepei/CasRel"<CasRel@noreply.github.com&gt;; 抄送: "tiger-jie"<1984223979@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [weizhepei/CasRel] extract_items 的问题 (#32) 其实还好，你可以理解为subject 和 object是一个多任务学习，最后是subject 的训练数据，会被多训练，相当于对subject任务数据做了过采样。 我觉得repo的实现不算最优，可以试试将数据按object拆分，应该训练过程 更稳定 &amp; 收敛更快 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tiger-jie** [comment]
您觉得如果一个text里面有多个三元组，在训练的时候repeat这个text，每个text只对应一个三元组。这种方法您觉得可取吗


 
---原始邮件---
发件人: "杨攀"<notifications@github.com&gt;
发送时间: 2020年10月10日 09:16:56
收件人: "weizhepei/CasRel"<CasRel@noreply.github.com&gt;;
抄送: "tiger-jie"<1984223979@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [weizhepei/CasRel] extract_items 的问题 (#32)




 
我觉得使用[unused] 副作用很大 &amp; 说不通，我觉得还是不这么用吧。就用下这个工作的思想就好
  
谢谢您的解答，我还有一个问题劳烦解答一下。对于很长的text来说，unused的使用会截断很多的单词，这种情况有没有什么好的解决办法
 …
 ---原始邮件--- 发件人: "杨攀"<notifications@github.com&gt; 发送时间: 2020年10月10日 09:06:59 收件人: "weizhepei/CasRel"<CasRel@noreply.github.com&gt;; 抄送: "tiger-jie"<1984223979@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [weizhepei/CasRel] extract_items 的问题 (#32) 其实还好，你可以理解为subject 和 object是一个多任务学习，最后是subject 的训练数据，会被多训练，相当于对subject任务数据做了过采样。 我觉得repo的实现不算最优，可以试试将数据按object拆分，应该训练过程 更稳定 &amp; 收敛更快 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Akeepers** [comment]
我觉得不好，如果repeat，对于subject任务， 其模型输入相同，但是golden label可能不一致，这样是有问题的

**Comment by senseandcalm** [comment]
> 这里的[unused1]其实类似[CLS]、[SEP]这样的标签，确实没有实际的意义，但却是必要的。我复现过作者的工作，刚开始结果很差，后来发现原因是没有加这个[unused1]标签。
> 一个词，在bert中，会被分成亚词，比如apple，可能会被拆成ap和ple，在作者的方法中，会识别一个实体的头位置和尾位置，如果不加边界标注，可能会将边界识别成ap，而不是ple。

对于中文任务，是不是没必要加这个[unused1]

**Comment by scarydemon2** [comment]
原本来打算在原本代码加一层GCN，但是有了这个unused就没法生成句法依存树了，处理邻接矩阵也复杂一些。
