### ISSUE TITLE
关于同一实体出现多次的问题

### ISSUE THREAD

**Issue by Gavin4th** [weizhepei/HBT#41]
作者在进行关系抽取的时候，有咩有考虑到同一个实体可能在一个句子中出现多次，举个例子，第一个实体参与了关系三元组的组成，而第二个句子没有参与这种情况

**Comment by Gavin4th** [comment]
第一次出现的实体参与了关系三元组的组成，而第二次出现的实体没有参与

**Comment by zlh-source** [comment]
> 第一次出现的实体参与了关系三元组的组成，而第二次出现的实体没有参与

举个例子应该会更好

**Comment by Gavin4th** [comment]
> > 第一次出现的实体参与了关系三元组的组成，而第二次出现的实体没有参与
> 
> 举个例子应该会更好



比如有一个句子   A and B  has relation， while A and C has no relation。而gold_data中只将第一个（A,B）提取成关系三元组，那么对于第二次出现的A，我们是不是不用去处理。我大体的意思就是想说代码中是否有考虑实体位置的地方，我觉得在extract_items()，作者好像考虑了。

还有一个地方就是，我们拿到了bert的分词之后，会得到tokens_id,那么我们直接将其输入到Input()层就好了嘛，不用去字典中取对应的词向量嘛，做subject entity的预测的时候，是不是不用使用句子的向量特征，我是小白，还望大佬解惑，谢谢

**Comment by mirrorQAQ** [comment]
> > > 第一次出现的实体参与了关系三元组的组成，而第二次出现的实体没有参与
> > 
> > 
> > 举个例子应该会更好
> 
> 比如有一个句子 A and B has relation， while A and C has no relation。而gold_data中只将第一个（A,B）提取成关系三元组，那么对于第二次出现的A，我们是不是不用去处理。我大体的意思就是想说代码中是否有考虑实体位置的地方，我觉得在extract_items()，作者好像考虑了。
> 
> 还有一个地方就是，我们拿到了bert的分词之后，会得到tokens_id,那么我们直接将其输入到Input()层就好了嘛，不用去字典中取对应的词向量嘛，做subject entity的预测的时候，是不是不用使用句子的向量特征，我是小白，还望大佬解惑，谢谢

词向量文件应该是给LSTM作为编码器的那个模型使用的，论文中有提到用LSTM做Encoder的模型是加载的预训练的Glove词向量， Bert本身输出的向量应该是比其他预训练的词向量都要好的， 所以不需要加载。
以及 Subject Entity的推理 始终是个序列标注的问题，和句向量特征没有关系。
个人理解。
