### ISSUE TITLE
小白提问：使用NYT数据集, 复现结果相差有10%，不知道问题在哪QAQ

### ISSUE THREAD

**Issue by syfshigechunvzuo** [weizhepei/HBT#48]
我完全按照readme的步骤
NYT数据集复现结果是0.8030150753768869（precision.)	0.7881627620221975(recall)	0.7955196017423797(F1) 
与论文中的89.7（precision）  89.5(recall)  89.6(F1) 相差甚远，可又不知道问题可能在哪

**Comment by SeanLee97** [comment]
I have run into a similar problem.
I cannot reproduce the reported results. Could you provide more experimental details or other tricks?

**Comment by syfshigechunvzuo** [comment]
> I have run into a similar problem.
> I cannot reproduce the reported results. Could you provide more experimental details or other tricks?
谢谢，我发现问题在哪了，我的训练数据集在generate.py.py处理后，复制到NYT文件夹下时，与其它数据集搞混了，改正和重新运行后，结果正确了

**Comment by Eiven575** [comment]
可以提供一下您的requirment.txt吗？谢谢了
