### ISSUE TITLE
webnlg得到的triplet.json文件里为什么很多实体都只有尾部

### ISSUE THREAD

**Issue by Coopercoppers** [weizhepei/HBT#49]
{
        "text": "Alan Bean ( of the United States ) was a crew member of NASA 's Apollo 12 under the commander David Scott .",
        "triple_list": [
            [
                "Bean",
                "was a crew member of",
                "12"
            ],
            [
                "Bean",
                "nationality",
                "States"
            ],
            [
                "12",
                "operator",
                "NASA"
            ],
            [
                "12",
                "commander",
                "Scott"
            ]
比如这个，实体不应该是alan bean和apollo 12嘛？用这样的数据测出来不能让人信服吧？

**Comment by martinambition** [comment]
老哥，你也发现了啊。。casrel用的copy‘r的，都有这个问题。
